# Generated by Django 3.1.2 on 2021-02-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(max_length=250)),
                ('channel_name', models.CharField(max_length=250)),
                ('heading', models.CharField(max_length=1000)),
                ('image1', models.ImageField(upload_to='news_images')),
                ('image2', models.ImageField(upload_to='news_images')),
                ('image3', models.ImageField(upload_to='news_images')),
                ('image4', models.ImageField(upload_to='news_images')),
                ('news_details', models.CharField(max_length=100000)),
            ],
        ),
    ]
