# Generated by Django 3.1.2 on 2021-02-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fine_arts', '0002_on_stage_event_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='off_stage_event_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=500)),
                ('day', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=500)),
                ('event_start_time', models.TimeField()),
                ('event_end_time', models.TimeField()),
                ('image1', models.ImageField(upload_to='event_images')),
                ('event_details', models.CharField(max_length=3000)),
            ],
        ),
    ]
