# Generated by Django 3.1.2 on 2021-02-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fine_arts', '0004_off_stage_participant_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='on_stage_participant_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=500)),
                ('group', models.CharField(max_length=50)),
                ('registration_number', models.CharField(max_length=250)),
                ('event', models.CharField(max_length=1000)),
                ('application_number', models.CharField(max_length=250)),
            ],
        ),
    ]
