# Generated by Django 3.1.2 on 2021-02-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fine_arts', '0007_on_stage_appeal_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='off_stage_participant_table',
            name='chest_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='on_stage_participant_table',
            name='chest_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
