# Generated by Django 3.1.2 on 2021-02-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fine_arts', '0011_result_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='on_stage_result_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('position', models.CharField(max_length=250)),
                ('group', models.CharField(max_length=250)),
                ('event', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameModel(
            old_name='result_table',
            new_name='off_stage_result_table',
        ),
    ]
