# Generated by Django 3.1.2 on 2021-02-25 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fine_arts', '0013_live_coverage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='live_coverage',
            old_name='video1',
            new_name='vedio1',
        ),
    ]
