# Generated by Django 3.1.2 on 2021-02-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fine_arts', '0014_auto_20210225_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live_coverage',
            name='vedio1',
            field=models.FileField(upload_to='live_coverage_media'),
        ),
    ]
