# Generated by Django 3.1.2 on 2021-02-25 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fine_arts', '0016_auto_20210225_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='live_coverage',
            old_name='vedio1',
            new_name='video1',
        ),
        migrations.RenameField(
            model_name='live_coverage',
            old_name='vedio_details',
            new_name='video_details',
        ),
    ]
