# Generated by Django 3.1.2 on 2021-02-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fine_arts', '0017_auto_20210225_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='officilas_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('role', models.CharField(max_length=250)),
            ],
        ),
    ]
