# Generated by Django 3.1.2 on 2021-02-25 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fine_arts', '0018_officilas_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='off_stage_participant_table',
            name='chest_number',
        ),
        migrations.RemoveField(
            model_name='on_stage_participant_table',
            name='chest_number',
        ),
    ]
